---
- name: "Read {{ _ls_scope }}"
  ansible.builtin.include_tasks: read.yml

- name: "Make the values of {{ _ls_scope }} available as variables"
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ _ls_data | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  no_log: true
