---
- name: "Read {{ load_secrets_scope }}"
  ansible.builtin.include_tasks: read.yml

- name: "Make the secret values available as variables: {{ load_secrets_scope }}"
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ _load_secrets_data | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  no_log: true
